### ISSUE TITLE
Private NPM registry support?

### ISSUE THREAD

**Issue by KarandikarMihir** [ameerthehacker/blazepack#1]
I wanted to try this on a real world project to see if it benefits us. But it doesn't seem to honor `.npmrc`? Really want to try this one out! Is there any way that readme doesn't cover to make this work?

**Comment by ameerthehacker** [comment]
I need to check on how sandpack handles .npmrc, will get back to you on this.

**Comment by ameerthehacker** [comment]
@KarandikarMihir v0.0.38 supports private npm packages 🚀 

We now honour the project level `.npmrc` file and if it is not found we fallback to user level `.npmrc` file and then finally the global `.npmrc` file. Currently we only support scoped private npm packages. To use the scoped private npm packages you need to fist login into the npm registry and add the scope config to `.npmrc`

```ini
@myorg:registry=https://registry.myorg.com
//registry.myorg.com/:_authToken=secrettoken
```

after above setup you should be able to use your private npm packages in blazepack 🎉 , let me know if you face any issues.
