### ISSUE TITLE
react app : _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by TheRakeshPurohit** [ameerthehacker/blazepack#17]
steps i followed: 

```
npm i -g blazepack
blazepack create my-cra --template=react
blazepack
```

Got; `_interopRequireDefault is not a function` on `localhost:3000`

running on linux 18.04

npm 7.5.6
node 14.15.1

**Comment by ameerthehacker** [comment]
@TheRakeshPurohit what is the blazepack version you are using?

**Comment by jyash97** [comment]
@TheRakeshPurohit can you confirm you ran the blazepack command in the my-cra folder

**Comment by ameerthehacker** [comment]
@TheRakeshPurohit this is an upstream issue affecting codesandbox itself https://github.com/codesandbox/codesandbox-client/issues/5506

**Comment by ameerthehacker** [comment]
@TheRakeshPurohit this has been fixed, please update to latest version of blazepack and try again, feel free to reopen the issue if the issue still persists

**Comment by TheRakeshPurohit** [comment]
![Screenshot from 2021-02-23 15-37-53](https://user-images.githubusercontent.com/26131905/108828785-4cbbb100-75ed-11eb-8a71-50dfc1f6505d.png)
![Screenshot from 2021-02-23 15-38-10](https://user-images.githubusercontent.com/26131905/108828794-4e857480-75ed-11eb-8f2b-187287efb5b2.png)

**Comment by TheRakeshPurohit** [comment]
Well, before and after updating blazepack, it works only in private window.

I have noticed that it shows error while i am running local react app in normal tab.

**Comment by ameerthehacker** [comment]
@TheRakeshPurohit try a hard reload in your normal tab, we are working on purging cache when you update to new versions of blazepack.
