### ISSUE TITLE
No dependencies error

### ISSUE THREAD

**Issue by Mista-T** [ameerthehacker/blazepack#2]
First up, this is great work and looks very promising, so thanks a lot!

I bet it's just a usage error on my part, but when I try to run "blazepack" or "npx blazepack" (doesn't make a difference) locally inside your provided example folders (either "react" or "vanilla"), I get the same following error:
"Uncaught Error: No dependencies specified, please specify either a package.json or dependencies."

What am I missing? :-)

Thanks Ameer!

**Comment by ameerthehacker** [comment]
@Mista-T did you try refreshing and did you run them at the root of the react folder in examples folder.

**Comment by Mista-T** [comment]
Hi Ameer, thanks for getting back to me!
Yes, I did run blazepack inside either the "examples/vanilla/" or the "examples/react/" folders, the ones containing the package.json files. 
Blazepack starts up fine in the terminal, but in the browser I only get a blank screen and the given error above.
Here's a console output, the warnings are only sandbox source maps though.
![blazepack-error-console](https://user-images.githubusercontent.com/38252860/108172751-7ceee580-70fd-11eb-8277-dcce6a5b3809.png)

**Comment by Mista-T** [comment]
Maybe it has to do with a mixed up initialization call on the Sandbox PreviewManager()?
It expects the following set of attributes: "(selector, sandboxInfo, options)", but gets supplied: "('#root', { showOpenInCodeSandbox: false })".
So I guess the second supplied argument should be the options, but as there are only two given, the PreviewManager doesn't have the correct "sandboxInfo" or mixes that up with the supplied "options"?
It does call it's internal function "createMissingPackageJSON(...)" later, which throws the error.
Maybe that helps.
Cheers!

**Comment by ameerthehacker** [comment]
@Mista-T got it can you try with latest version?

**Comment by Mista-T** [comment]
@ameerthehacker I don't see a newer version yet, sorry.

**Comment by Mista-T** [comment]
Re-checked again with blazepack@0.0.13 and the same error is being thrown, sorry.

**Comment by ameerthehacker** [comment]
can you try it on a fresh create react app?

**Comment by Mista-T** [comment]
Hi Ameer, I tried again with a freshly globally installed blazepack v0.0.15.
Created a new react template project in an empty folder:
```
[XY:path user$ blazepack start cra --template=react
Downloading the template react...
⚡ Blazepack dev server running at http://localhost:3000
Unhandled Sandpack error while running the app.
No dependencies specified, please specify either a package.json or dependencies.
Terminating the server
```
Same error when I manually change into the newly created project folder ("cra" in my case above) and start blazepack from there.

I'm short on time right now, but hope to be able to dig into code a bit later and maybe could help out here. Cheers!

**Comment by ameerthehacker** [comment]
@Mista-T this seems weird which os are you using?

**Comment by Mista-T** [comment]
I'm (still) on macOS Mojave, v10.14.4
Using Node v12.13.0 in the terminal.

**Comment by jyash97** [comment]
I tried the same command and it works for me. Though I tried it with `npx` but it should work with global setup as well. Are you seeing the created directory with the name `cra` ?

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/108622468-0f291d80-745f-11eb-8401-a5f8f63cf1b2.png)

Another attempt: 

![image](https://user-images.githubusercontent.com/31458531/108622513-60391180-745f-11eb-90ab-aceb5ca1d6cb.png)

But it was working fine yesterday :(

Any possible problems/debugging thing i can try..?

**Comment by jyash97** [comment]
Can you verify that you have package.json and in that you have dependencies or `main` field ?

If not try adding `main` field in package.json

**Comment by sahilrajput03** [comment]
> Can you verify that you have package.json and in that you have dependencies and `main` field ?
> 
> If not try adding `main` field in package.json

Sure,

![image](https://user-images.githubusercontent.com/31458531/108622792-16512b00-7461-11eb-9fae-410618c7fcf1.png)

**Comment by sahilrajput03** [comment]
Ok got it working, I guess its realted to my earlier directory only, but in other places it works great!!

![image](https://user-images.githubusercontent.com/31458531/108623582-bb6e0280-7465-11eb-9996-d8de60116d36.png)

@Mista-T , can you try running blazepack creat command somewhere else than your earlier directory ..?

**Comment by ameerthehacker** [comment]
@Mista-T closing this, feel free to reopen if you are still facing the issues.

**Comment by Mista-T** [comment]
Hi guys, sorry for being off for a few days, here's what happened after I tried with the latest blazepack version (v0.0.17) and a fresh, empty directory on my machine:

```
CT:blazepack-test christianthone$ blazepack create cra --template=react
Downloading the template react...
CT:blazepack-test christianthone$ cd cra/
CT:cra christianthone$ blazepack
⚡ Blazepack dev server running at http://localhost:3000
Unhandled Sandpack error while running the app.
Cannot read property 'code' of undefined
Terminating the server

```

**Comment by Mista-T** [comment]
Sure thing, thanks for sticking with me!

```
$ blazepack --version : v0.0.17
$ node -v : v12.13.0
$ npm -v : 6.14.5
$ npx -v : 6.14.5
```
I will try again with an updated node version (v14) too later.

**Comment by Mista-T** [comment]
Sorry guys, it just doesn't work (on my machine):

I updated to the latest LTS node v14.15.5 and then:

```
$ npx blazepack create cra --template=react
npx: Installed 74 in 3.617s
Downloading the template react...
$ cd cra
$ npx blazepack
⚡ Blazepack dev server running at http://localhost:3000
Unhandled Sandpack error while running the app.
Cannot read property 'code' of undefined
Terminating the server
```

**Comment by ameerthehacker** [comment]
hey give it a try by hard reload and also by trying it in incognito

**Comment by ameerthehacker** [comment]
@Mista-T if you were running on a linux machine, we just released a bug fix for that, do try out the latest version and let me know if you still face any issues
