### ISSUE TITLE
Add service worker to cache npm packages alone

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/blazepack#22]

**Comment by BA1RY** [comment]
I want to work on this @ameerthehacker 😄

**Comment by jyash97** [comment]
Hey @BA1RY @ameerthehacker  👋 , 

We are already caching the dependencies and the sandpack files, since we are using `unpkg` which sends the cache headers and thus caching all the files.

**Comment by ameerthehacker** [comment]
@jyash97 agreed @BA1RY I don't think service worker is needed anymore. Don't worry blazepack is needs more features.
