### ISSUE TITLE
Add help command

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/blazepack#29]
* We use a light weight cli tool called minimist and it does not come with support for help command, so we need to build a help command which provides info on available commands
* It should follow the same format as standard linux cli, for ex.

![Screenshot 2021-02-26 at 00 08 19](https://user-images.githubusercontent.com/15448192/109200556-c5c23080-77c6-11eb-83f7-dfb63e833ac9.png)

* Read the README.md to provide help on all commands

**Comment by dhruwlalan** [comment]
I would like to work on this.

**Comment by ameerthehacker** [comment]
@dhruwlalan sure

**Comment by jyash97** [comment]
This has been released in v0.0.27 to npm. Thanks for helping us making blazepack better @dhruwlalan  🎉
