### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by mananchawla2005** [ameerthehacker/blazepack#3]
Hi when I tried running blazepack inside a vue 3 project, localhost:3000 shows complete blank screen. Am i doing something wrong?

**Comment by ameerthehacker** [comment]
@mananchawla2005 can you please share the vue3 project repo if you can

**Comment by sahilrajput03** [comment]
It happened with me too.., like completely blank screen when i used it with react boiler code as mentioned in docs with command:

```
npm i -g blazepack
blazepack create my-cra --template=react
cd my-cra
blazepack
```

Can you tell your?

```
node -v
npm -v
npx -v
```

mine is like this:

```
node -v : v14.15.4
npm -v : 7.5.2
npx -v : 7.5.2
```

**If you prefer `yarn` do tell, or some other npm package manager do tell that please..!**

### My screen after running `blazepack` command:

![image](https://user-images.githubusercontent.com/31458531/108326225-0383ef80-71f0-11eb-8d02-63d3be0a4403.png)

What is the matter @ameerthehacker ?

**Comment by ameerthehacker** [comment]
@sahilrajput03 does this happen with other templates also, and did you had internet connection while trying this out?

**Comment by sahilrajput03** [comment]
> @sahilrajput03 does this happen with other templates also, and did you had internet connection while trying this out?

Internet is good for sure.., I am now gonna try other templates too.., wait a minute..

**Comment by sahilrajput03** [comment]
for angular its like: 
![image](https://user-images.githubusercontent.com/31458531/108328028-1e576380-71f2-11eb-96a3-c604a5d0e57a.png)

**Comment by ameerthehacker** [comment]
@sahilrajput03 I think I found a release will cut a release in sometime

**Comment by sahilrajput03** [comment]
FYI: I noticed some download are happening in background when i try to reload the page(its done with preact template), i.e., `blazepack start my-preact-app --template=preact`. Check it [here](https://www.youtube.com/watch?v=QYsXdscksPI).

**Comment by ameerthehacker** [comment]
@sahilrajput03 I have fixed the issue, please try with the latest version

**Comment by sahilrajput03** [comment]
> @sahilrajput03 I have fixed the issue, please try with the latest version

![image](https://user-images.githubusercontent.com/31458531/108331823-282e9600-71f5-11eb-90dd-eb1c9ccc71db.png)

Amazing!!! <3 <3 <3

**Comment by sahilrajput03** [comment]
@mananchawla2005 , you can close this issue I guess!

**Comment by ameerthehacker** [comment]
@sahilrajput03 thanks for confirming and hopefully it will work for you also @mananchawla2005
