### ISSUE TITLE
How do I add custom transpilers

### ISSUE THREAD

**Issue by ClassicOldSong** [ameerthehacker/blazepack#35]
I wrote a custom template engine which uses a custom syntax. How could I get it transpiled using blazepack?

See here for a quick demo: https://codesandbox.io/s/efjs-starter-template-n42jy?file=/src/app.eft

**Comment by ameerthehacker** [comment]
@ClassicOldSong we support only client based codesandbox templates as all out transpilation happens in the browser. You can add custom babel plugins and macros by using .babelrc file in the vanilla template.

**Comment by ClassicOldSong** [comment]
Yeah that's what exactly what I want to ask. Most transpilers(not babel based) could run directly in browser including the one I mentioned above. Is there any way adding it to blazepack or make blazepack recognize it as a plugin?

**Comment by ameerthehacker** [comment]
@ClassicOldSong not currently as by design we don't meddle with sandpack which actually does the bundling, may be in the future if we expand the scope of blazepack we may add some hooks to sandpack bundler so that we can implement some plugins for such use cases to work.
