### ISSUE TITLE
Unhandled Sandpack error while running the app.

### ISSUE THREAD

**Issue by Logan1x** [ameerthehacker/blazepack#36]
I created a new sandbox on code sandbox and clone the sandbox using `blazepack clone`. And when I am trying to run the project, with `blazepack start` command, it shows 
```BASH
$ blazepack start
⚡ Blazepack dev server running at http://localhost:3000
❌ Unhandled Sandpack error while running the app.
❌ e['/package.json'] is undefined
Terminating the server

```
`package.json` is available in the folder. Also, the 2nd and 3rd line error doesn't load till I visit the http://localhost:3000 in the browser.

Sandbox link : https://codesandbox.io/s/random-user-3cvug

**Comment by Logan1x** [comment]
Its not just with codesandbox clone, I am getting even when creating new project with blazepack create and running.

```bash
Blazepack dev server running at http://localhost:3000
❌ Unhandled Sandpack error while running the app.
❌ Cannot read property 'code' of undefined
Terminating the server
```

**Comment by ameerthehacker** [comment]
@Logan1x what is the version of blazepack you are using? I cannot replicate the same on `v0.0.45`

**Comment by Logan1x** [comment]
I am on version `v0.0.45`. Is there a way I can send you logs?

**Comment by ameerthehacker** [comment]
@Logan1x please share info on your os, node and npm version

**Comment by Logan1x** [comment]
Node version : `v14.5.0`
NPM : `7.6.3`
OS : `Manjaro 20.0.3`

**Comment by ameerthehacker** [comment]
@Logan1x this looks little tricky and machine specific, it would be great if you can join our discord channel and we can meet to investigate the issue on your machine

**Comment by Logan1x** [comment]
Sure. I'll connect with you there.

**Comment by ameerthehacker** [comment]
@all-contributors please add @Logan1x for bug

**Comment by ameerthehacker** [comment]
@Logan1x have released a fix for this, do try out and let me know.

**Comment by Logan1x** [comment]
Thank you for the update. My issue is solved now 🍻
