### ISSUE TITLE
May be we can make it to use `bpk add <package>` 😎

### ISSUE THREAD

**Issue by saideepesh000** [ameerthehacker/blazepack#37]
We can even make it faster with optional 3 word command something like `bpk or bpl`

**Comment by ameerthehacker** [comment]
@sahilrajput03 that is a great idea and you have it in v0.0.49 of blazepack

<img width="886" alt="bpk" src="https://user-images.githubusercontent.com/15448192/112021468-55a19300-8b57-11eb-83e5-a4c6ee273325.png">

**Comment by ameerthehacker** [comment]
@all-contributors please add @sahilrajput03 for ideas

**Comment by ameerthehacker** [comment]
@all-contributors please add @saideepesh000 for ideas

**Comment by sahilrajput03** [comment]
> @sahilrajput03 that is a great idea and you have it in v0.0.49 of blazepack
> 
> <img width="886" alt="bpk" src="https://user-images.githubusercontent.com/15448192/112021468-55a19300-8b57-11eb-83e5-a4c6ee273325.png">
> 

You accidentally tagged me..:)

**Comment by ameerthehacker** [comment]
@sahilrajput03 ha ha yes Github auto suggest messed it up

**Comment by saideepesh000** [comment]
Hey @ameerthehacker, thanks for adding me as the contributor, would love to help you more 👍

**Comment by ameerthehacker** [comment]
Sure @saideepesh000 that would be great and we always encourage and appreciate all kinds of contributions and not just code 😀
