### ISSUE TITLE
codesandbox vue3 base project bug

### ISSUE THREAD

**Issue by zucatti** [ameerthehacker/blazepack#4]
Hi,
first of all, blazepack is awesome ! thx guy for sharing this project with us.
I ran an exception working with safari, it's working fine with chrome, firefox. 
The project I use is just the base vue3 project in codesandbox (https://codesandbox.io/s/frosty-einstein-7z05w)
  <img
    alt="Vue logo"
    src="./assets/logo.png"
  />
give me Failed to execute 'fetch' on 'Window': Failed to parse URL from ... (binary png follows)
I if remove the img tag, all is working fine.
I'm using macos safari-chrome-firefox

Keep up the good work ;-)

**Comment by ameerthehacker** [comment]
@zucatti thanks for sharing this, will check it and update you

**Comment by ameerthehacker** [comment]
@zucatti can you please try now with the latest version.

**Comment by ameerthehacker** [comment]
@zucatti closing the issue, please feel free to reopen if you are still facing the issue
