### ISSUE TITLE
`bpk start` is closing terminal on windows

### ISSUE THREAD

**Issue by saideepesh000** [ameerthehacker/blazepack#46]
version: 0.0.59
![bpkstart](https://user-images.githubusercontent.com/43727167/112746972-054f8880-8fd0-11eb-9a14-d03bbaf550f3.gif)

**Comment by ameerthehacker** [comment]
@saideepesh000 please share your node and os version info

**Comment by ameerthehacker** [comment]
@all-contributors add @saideepesh000 for bug

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 please share your node and os version info

Node v12.20.1
windows 10

**Comment by ameerthehacker** [comment]
@saideepesh000 I checked it with cmd and power-shell and it happens in them both, but weirdly the new windows terminal (https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701) just works fine. Was the previous versions of blazepack working fine for you?

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 I checked it with cmd and power-shell and it happens in them both, but weirdly the new windows terminal (https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701) just works fine. Was the previous versions of blazepack working fine for you?

Yes, previous versions were working fine, I think I directly upgraded from 52 to 59

**Comment by ameerthehacker** [comment]
@saideepesh000 I recently updated one of our lib called `open` and I think that is what causing it

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 I recently updated one of our lib called `open` and I think that is what causing it. I will probably downgrade it back.

My Browseri is Firefox, I could see there is not option for firefox [here](https://github.com/ameerthehacker/blazepack/blob/96dbc57167e29fc800d70f11f37688b2591f9634/src/open-browser/index.js#L9)

**Comment by ameerthehacker** [comment]
@saideepesh000 yes but that piece of code only runs for mac os users

**Comment by ameerthehacker** [comment]
@saideepesh000 can you try to uninstall blazepack and install 0.0.57 version

```
npm i -g blazepack@0.0.57
```

and check whether the issue still exists

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 can you try to uninstall blazepack and install 0.0.57 version
> 
> ```
> npm i -g blazepack@0.0.57
> ```
> 
> and check whether the issue still exists

Ya, it's working fine on 57 👍

**Comment by ameerthehacker** [comment]
@saideepesh000 ok I updated `open` in v0.0.58 so that is the issue, will downgrade it in some time and will cut a release.

**Comment by ameerthehacker** [comment]
@saideepesh000 this issue has been fixed in v0.0.60, please check and let me know.

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 this issue has been fixed in v0.0.60, please check and let me know.

Yayyy it's working, but it's automatically starting the localhost 😄

**Comment by ameerthehacker** [comment]
@saideepesh000 did not get you, what you mean by automatically starting the localhost?

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 did not get you, what you mean by automatically starting the localhost?

I meant browser 😅

**Comment by ameerthehacker** [comment]
yes @saideepesh000 that is the expected behaviour right?

**Comment by saideepesh000** [comment]
> 
> 
> yes @saideepesh000 that is the expected behaviour right?

oh, lol, I'm not sure why, up until now I was not seeing this, I manually type localhost:3000, looool

**Comment by ameerthehacker** [comment]
@saideepesh000 there was a bug in windows and linux previously which prevented automatically opening the browser and it was recently fixed. If you don't want this behaviour you can do something like this

```
setx BROWSER none

bpk start
```
