### ISSUE TITLE
Show App path and how to start

### ISSUE THREAD

**Issue by SBhanushali** [ameerthehacker/blazepack#48]
When we use blazepack create app-name --template=react without open flag it just shows project created and no further instructions 
<img width="729" alt="Screenshot 2021-03-28 at 4 16 39 PM" src="https://user-images.githubusercontent.com/29128433/112749605-fd4c1480-8fe0-11eb-8a97-88cdd14e08b3.png">
Instead we can show
📥 Downloading template... \
📁 Creating files & directories \
✅ Project created \
cd app-name && blazepack start 

when used with open flag we can show relative app folder path.

**Comment by ameerthehacker** [comment]
@SBhanushali yes please goahead

**Comment by ameerthehacker** [comment]
@all-contributors please add @SBhanushali for ideas

**Comment by saideepesh000** [comment]
@SBhanushali, if you're not working on it let me know, I can work on it.

**Comment by SBhanushali** [comment]
@saideepesh000 I'm working on it

**Comment by ameerthehacker** [comment]
@saideepesh000 @SBhanushali this has been released in v0.0.62
