### ISSUE TITLE
Give an error log to start server on other port

### ISSUE THREAD

**Issue by saideepesh000** [ameerthehacker/blazepack#50]
When a port is taken, we need to show user to start current server on other port. I'm not sure why this isn't working in production, in development it's working

### Development

![Screenshot (45)](https://user-images.githubusercontent.com/43727167/112751825-98e38200-8fed-11eb-8b51-feb99d885796.png)

![Screenshot (46)](https://user-images.githubusercontent.com/43727167/112751832-9c770900-8fed-11eb-93b2-fb43f7d20ca5.png)

### Production

![Screenshot (44)](https://user-images.githubusercontent.com/43727167/112751748-2a9ebf80-8fed-11eb-8c5b-f6a80ed8a4ba.png)

**Comment by saideepesh000** [comment]
Hey @ameerthehacker, just a quick doubt, how to check these kind of things while developing for production.

**Comment by ameerthehacker** [comment]
@saideepesh000 by default it should run in production, in mac `process.env.NODE_ENV` by default is null. I think in windows it is `development` which is actually causing the issue. If you can change

```
if (process.env.NODE_ENV !== 'test') {
 ...
}
```

During development we can set NODE_ENV to test for stack trace

**Comment by saideepesh000** [comment]
@ameerthehacker  Shall I raise a PR

**Comment by ameerthehacker** [comment]
@saideepesh000 yes please go ahead

**Comment by ameerthehacker** [comment]
@saideepesh000 the fix has been released in v0.0.61
