### ISSUE TITLE
Angular template rough edges

### ISSUE THREAD

**Issue by kylecordes** [ameerthehacker/blazepack#6]
The Angular template brings in the latest Angular, but names the Angular CLI config file with a very old name `.angular-cli.json`, which has fallen mostly into disuse.

Then, it creates a package.json with a run script that runs Angular CLI, i.e. it doesn't actually run blazepack.  It took a minute to realize this.

Therefore, desired features:

* Update the Angular template so its output looks like a 2021 Angular example.
* Make it so the command people usually try first, “npm run start”, does the “right thing”.

**Comment by ameerthehacker** [comment]
@kylecordes thanks for sharing this, will consider them during the next release.
